blank_issues_enabled: true
contact_links:
  - name: 💬 Support
    url: https://discord.gg/Ft6YB6yjAC
    about: "If you need help with the server/plugin or have a question please join the Discord server and do so by creating a ticket via #info."